AGARI_TOURNAMENT_ID = 307
AGARI_SECOND_STAGE_COEFFICIENT = 3.18
AGARI_FIRST_STAGE_COEFFICIENT = 2.73

HARDCODED_COEFFICIENTS = {
    307: {
        1821: AGARI_SECOND_STAGE_COEFFICIENT,
        154:  AGARI_SECOND_STAGE_COEFFICIENT,
        252:  AGARI_SECOND_STAGE_COEFFICIENT,
        118:  AGARI_SECOND_STAGE_COEFFICIENT,
        176:  AGARI_SECOND_STAGE_COEFFICIENT,
        79:   AGARI_SECOND_STAGE_COEFFICIENT,
        69:   AGARI_SECOND_STAGE_COEFFICIENT,
        119:  AGARI_SECOND_STAGE_COEFFICIENT,
        81:   AGARI_FIRST_STAGE_COEFFICIENT,
        162:  AGARI_FIRST_STAGE_COEFFICIENT,
        78:   AGARI_FIRST_STAGE_COEFFICIENT,
        256:  AGARI_FIRST_STAGE_COEFFICIENT,
        52:   AGARI_FIRST_STAGE_COEFFICIENT,
        254:  AGARI_FIRST_STAGE_COEFFICIENT,
        159:  AGARI_FIRST_STAGE_COEFFICIENT,
        158:  AGARI_FIRST_STAGE_COEFFICIENT,
        134:  AGARI_FIRST_STAGE_COEFFICIENT,
        156:  AGARI_FIRST_STAGE_COEFFICIENT,
        151:  AGARI_FIRST_STAGE_COEFFICIENT,
        83:   AGARI_FIRST_STAGE_COEFFICIENT,
        190:  AGARI_FIRST_STAGE_COEFFICIENT,
        70:   AGARI_FIRST_STAGE_COEFFICIENT,
        182:  AGARI_FIRST_STAGE_COEFFICIENT,
        1942: AGARI_FIRST_STAGE_COEFFICIENT
    }
}
