# Generated by Django 2.2.6 on 2019-10-24 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('player', '0006_auto_20190521_0903'),
    ]

    operations = [
        migrations.CreateModel(
            name='MSAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.PositiveIntegerField(unique=True)),
                ('account_name', models.CharField(blank=True, max_length=255, null=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ms', to='player.Player')),
            ],
        ),
        migrations.CreateModel(
            name='MSAccountStatistic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.PositiveSmallIntegerField(choices=[[0, 'Four player'], [1, 'Three player']])),
                ('rank', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('points', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('games', models.PositiveIntegerField(blank=True, null=True)),
                ('average_place', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('first_place', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('second_place', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('third_place', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fourth_place', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='mahjong_soul.MSAccount')),
            ],
        ),
    ]
