# Generated by Django 2.2.6 on 2019-12-31 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mahjong_soul', '0003_mspointshistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='msaccountstatistic',
            name='hanchan_first_place',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='msaccountstatistic',
            name='hanchan_fourth_place',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='msaccountstatistic',
            name='hanchan_second_place',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='msaccountstatistic',
            name='hanchan_third_place',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='msaccountstatistic',
            name='tonpusen_first_place',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='msaccountstatistic',
            name='tonpusen_fourth_place',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='msaccountstatistic',
            name='tonpusen_second_place',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='msaccountstatistic',
            name='tonpusen_third_place',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
