# Generated by Django 4.2.9 on 2024-03-04 07:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mahjong_soul", "0005_auto_20210410_0502"),
    ]

    operations = [
        migrations.AddField(
            model_name="msaccount",
            name="last_update",
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
