# Generated by Django 4.2.9 on 2024-03-04 07:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mahjong_soul", "0007_alter_msaccount_last_update"),
    ]

    operations = [
        migrations.AlterField(
            model_name="msaccount",
            name="last_update",
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
