# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-16 18:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('player', '0001_initial'),
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('name_en', models.CharField(max_length=255, null=True)),
                ('name_ru', models.CharField(max_length=255, null=True)),
                ('slug', models.SlugField()),
                ('website', models.URLField(blank=True, null=True)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='settings.City')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='settings.Country')),
                ('players', models.ManyToManyField(related_name='clubs', to='player.Player')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
