# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-22 12:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='players',
            field=models.ManyToManyField(blank=True, related_name='clubs', to='player.Player'),
        ),
    ]
