# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-22 13:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0002_auto_20171222_1211'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='lat',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=21, null=True),
        ),
        migrations.AddField(
            model_name='club',
            name='lng',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=21, null=True),
        ),
    ]
