# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-31 01:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0003_auto_20171222_1304'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='club',
            options={'ordering': ['name']},
        ),
    ]
