# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-01-15 07:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0005_club_pantheon_ids'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='rating_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='club',
            name='rating_description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='club',
            name='rating_description_ru',
            field=models.TextField(blank=True, null=True),
        ),
    ]
