# -*- coding: utf-8 -*-

# Generated by Django 3.2 on 2021-04-16 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0007_alter_club_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='club',
            name='rating_description',
        ),
        migrations.RemoveField(
            model_name='club',
            name='rating_description_en',
        ),
        migrations.RemoveField(
            model_name='club',
            name='rating_description_ru',
        ),
        migrations.AddField(
            model_name='club',
            name='current_club_rating_pantheon_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
