# Generated by Django 4.2.9 on 2024-05-11 08:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("club", "0008_auto_20210416_0223"),
    ]

    operations = [
        migrations.AddField(
            model_name="club",
            name="new_pantheon_ids",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
