# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-26 16:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('club', '0002_club_timezone'),
        ('player', '0002_player_pantheon_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClubRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('player_string', models.CharField(blank=True, max_length=255, null=True)),
                ('games_count', models.PositiveIntegerField()),
                ('average_place', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ippatsu_chance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('average_dora_in_hand', models.DecimalField(decimal_places=2, max_digits=10)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='club.Club')),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='player.Player')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ClubSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('date', models.DateTimeField()),
                ('pantheon_id', models.CharField(blank=True, max_length=255, null=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='club_sessions', to='club.Club')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ClubSessionResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('player_string', models.CharField(blank=True, max_length=255, null=True)),
                ('order', models.PositiveSmallIntegerField()),
                ('place', models.PositiveSmallIntegerField()),
                ('score', models.IntegerField()),
                ('club_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='club_games.ClubSession')),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='player.Player')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
