# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-27 05:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0002_club_timezone'),
        ('club_games', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClubSessionSyncData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('last_session_id', models.PositiveIntegerField(blank=True, null=True)),
                ('club', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sync_info', to='club.Club')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='clubrating',
            name='feed_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clubrating',
            name='first_place',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clubrating',
            name='fourth_place',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clubrating',
            name='second_place',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clubrating',
            name='third_place',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
