# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-01 04:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club_games', '0004_clubrating_successful_riichi'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubsession',
            name='pantheon_event_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
