# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-08-11 14:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club_games', '0005_clubsession_pantheon_event_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clubrating',
            name='average_dora_in_hand',
        ),
        migrations.RemoveField(
            model_name='clubrating',
            name='feed_percentage',
        ),
        migrations.RemoveField(
            model_name='clubrating',
            name='ippatsu_chance',
        ),
        migrations.RemoveField(
            model_name='clubrating',
            name='open_hand',
        ),
        migrations.RemoveField(
            model_name='clubrating',
            name='successful_riichi',
        ),
        migrations.AddField(
            model_name='clubrating',
            name='rank',
            field=models.PositiveSmallIntegerField(blank=True, choices=[[0, '新人'], [1, '９級'], [2, '８級'], [3, '７級'], [4, '６級'], [5, '５級'], [6, '４級'], [7, '３級'], [8, '２級'], [9, '１級'], [10, '初段'], [11, '二段'], [12, '三段'], [13, '四段'], [14, '五段'], [15, '六段'], [16, '七段'], [17, '八段'], [18, '九段'], [19, '十段'], [20, '天鳳位']], default=None, null=True),
        ),
    ]
