# Generated by Django 5.2.9 on 2025-12-27 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tournament", "0057_tournament_tournament_games_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="YagiKeijiCupSettings",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("is_hidden", models.BooleanField(default=False)),
                (
                    "majsoul_tournament",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="majsoul_tournament",
                        to="tournament.tournament",
                    ),
                ),
                (
                    "tenhou_tournament",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tenhou_tournament",
                        to="tournament.tournament",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
