# Generated by Django 5.2.9 on 2025-12-27 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("yagi_keiji_cup", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="yagikeijicupsettings",
            name="is_main",
            field=models.BooleanField(default=False),
        ),
    ]
