# Generated by Django 5.2.9 on 2025-12-27 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("player", "0018_player_is_hide_ms_activity_and_more"),
        ("yagi_keiji_cup", "0002_yagikeijicupsettings_is_main"),
    ]

    operations = [
        migrations.CreateModel(
            name="YagiKeijiCupResults",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("team_name", models.TextField(blank=True, default="", null=True)),
                ("tenhou_player_place", models.PositiveIntegerField(blank=True, null=True, unique=True)),
                ("majsoul_player_place", models.PositiveIntegerField(blank=True, null=True, unique=True)),
                ("team_scores", models.FloatField(default=0)),
                (
                    "majsoul_player",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="yagi_keiji_cup_player_majsoul_results",
                        to="player.player",
                    ),
                ),
                (
                    "tenhou_player",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="yagi_keiji_cup_player_tenhou_results",
                        to="player.player",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
