# Generated by Django 5.2.9 on 2025-12-27 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("yagi_keiji_cup", "0003_yagikeijicupresults"),
    ]

    operations = [
        migrations.AddField(
            model_name="yagikeijicupresults",
            name="majsoul_player_game_count",
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="yagikeijicupresults",
            name="tenhou_player_game_count",
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
    ]
