# Generated by Django 5.2.9 on 2025-12-27 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("yagi_keiji_cup", "0004_yagikeijicupresults_majsoul_player_game_count_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="yagikeijicupresults",
            name="majsoul_player_game_count",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="yagikeijicupresults",
            name="majsoul_player_place",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="yagikeijicupresults",
            name="tenhou_player_game_count",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="yagikeijicupresults",
            name="tenhou_player_place",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
