# Generated by Django 5.2.9 on 2025-12-28 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("yagi_keiji_cup", "0005_alter_yagikeijicupresults_majsoul_player_game_count_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="yagikeijicupresults",
            name="team_name",
            field=models.TextField(blank=True, default="", null=True, unique=True),
        ),
    ]
