# Generated by Django 5.2.9 on 2026-01-02 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("online", "0027_tournamentnotification_lang"),
        ("yagi_keiji_cup", "0007_alter_yagikeijicupresults_team_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="yagikeijicupresults",
            name="majsoul_player",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="yagi_keiji_cup_player_majsoul_results",
                to="online.tournamentplayers",
            ),
        ),
        migrations.AlterField(
            model_name="yagikeijicupresults",
            name="tenhou_player",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="yagi_keiji_cup_player_tenhou_results",
                to="online.tournamentplayers",
            ),
        ),
    ]
