# Generated by Django 5.2.9 on 2026-01-09 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("yagi_keiji_cup", "0008_alter_yagikeijicupresults_majsoul_player_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="yagikeijicupresults",
            name="majsoul_player_avg_place",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="yagikeijicupresults",
            name="tenhou_player_avg_place",
            field=models.FloatField(default=0),
        ),
    ]
