# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-16 18:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=255)),
                ('first_name_en', models.CharField(max_length=255, null=True)),
                ('first_name_ru', models.CharField(max_length=255, null=True)),
                ('last_name', models.CharField(max_length=255)),
                ('last_name_en', models.CharField(max_length=255, null=True)),
                ('last_name_ru', models.CharField(max_length=255, null=True)),
                ('slug', models.SlugField(unique=True)),
                ('gender', models.PositiveSmallIntegerField(choices=[[0, 'f'], [1, 'm'], [2, '']], default=2)),
                ('is_replacement', models.BooleanField(default=False)),
                ('is_hide', models.BooleanField(default=False)),
                ('inner_rating_score', models.PositiveSmallIntegerField(default=0)),
                ('inner_rating_place', models.PositiveIntegerField(default=0)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='settings.City')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='settings.Country')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
