# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-28 14:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='ema_id',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
