# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-16 05:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='inner_rating_place',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='inner_rating_score',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
