# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-26 13:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='pantheon_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
