# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-27 05:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0002_player_pantheon_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenhouNickname',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('tenhou_username', models.CharField(max_length=8)),
                ('username_created_at', models.DateField()),
                ('rank', models.PositiveSmallIntegerField(choices=[[0, '新人'], [1, '9級'], [2, '8級'], [3, '7級'], [4, '6級'], [5, '5級'], [6, '4級'], [7, '3級'], [8, '2級'], [9, '1級'], [10, '初段'], [11, '二段'], [12, '三段'], [13, '四段'], [14, '五段'], [15, '六段'], [16, '七段'], [17, '八段'], [18, '九段'], [19, '十段'], [20, '天鳳位']])),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenhou', to='player.Player')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
