# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-12-26 04:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0002_player_pantheon_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerERMC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('state', models.PositiveSmallIntegerField(choices=[[0, 'точно едет'], [1, 'скорее всего едет'], [2, 'пока сомневается, но скорее всего не едет'], [3, 'игрок пока ничего не ответил'], [4, 'игрок пока что не проходит, но готов ехать, если появится квота'], [5, 'точно не едет'], [6, 'деда']])),
                ('federation_member', models.BooleanField(default=False)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='player.Player')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
