# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-13 04:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0003_tenhounickname'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenhouStatistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lobby', models.PositiveSmallIntegerField(choices=[[0, 'Kyu lobby'], [1, 'Dan lobby'], [2, 'Upperdan lobby'], [3, 'Phoenix lobby']])),
                ('played_games', models.PositiveIntegerField(default=0)),
                ('average_place', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('first_place', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('second_place', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('third_place', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fourth_place', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
            options={
                'ordering': ['lobby'],
            },
        ),
        migrations.AlterModelOptions(
            name='tenhounickname',
            options={'ordering': ['rank']},
        ),
        migrations.AddField(
            model_name='tenhounickname',
            name='average_place',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='tenhounickname',
            name='played_games',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tenhounickname',
            name='rank',
            field=models.PositiveSmallIntegerField(choices=[[0, '新人'], [1, '９級'], [2, '８級'], [3, '７級'], [4, '６級'], [5, '５級'], [6, '４級'], [7, '３級'], [8, '２級'], [9, '１級'], [10, '初段'], [11, '二段'], [12, '三段'], [13, '四段'], [14, '五段'], [15, '六段'], [16, '七段'], [17, '八段'], [18, '九段'], [19, '十段'], [20, '天鳳位']]),
        ),
        migrations.AddField(
            model_name='tenhoustatistics',
            name='tenhou_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='player.TenhouNickname'),
        ),
    ]
