# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-12-26 09:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0003_playerermc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerermc',
            name='player',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ermc', to='player.Player'),
        ),
    ]
