# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-29 03:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0004_auto_20171229_0157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='inner_rating_place',
        ),
        migrations.RemoveField(
            model_name='player',
            name='inner_rating_score',
        ),
    ]
