# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-13 05:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0004_auto_20180413_0437'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tenhounickname',
            options={'ordering': ['-rank']},
        ),
    ]
