# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-05-21 09:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0005_auto_20190216_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerermc',
            name='state',
            field=models.PositiveSmallIntegerField(choices=[[0, 'точно едет'], [1, 'скорее всего едет'], [2, 'пока сомневается, но скорее всего не едет'], [3, 'игрок пока ничего не ответил'], [4, 'игрок пока что не проходит, но готов ехать, если появится квота'], [5, 'точно не едет'], [6, 'деда'], [7, 'игрок замены'], [8, 'не деда (судья)']]),
        ),
    ]
