# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-31 01:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0005_auto_20171229_0323'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='player',
            options={'ordering': ['last_name']},
        ),
    ]
