# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-14 08:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0005_auto_20180413_0555'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenhounickname',
            name='end_pt',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tenhounickname',
            name='last_played_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tenhounickname',
            name='pt',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
