# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-14 12:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0006_auto_20180414_0811'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenhounickname',
            name='is_main',
            field=models.BooleanField(default=True),
        ),
    ]
