# -*- coding: utf-8 -*-

# Generated by Django 2.2.6 on 2019-12-18 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0006_auto_20190521_0903'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerTitle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('text', models.CharField(max_length=255)),
                ('text_en', models.CharField(max_length=255, null=True)),
                ('text_ru', models.CharField(max_length=255, null=True)),
                ('color', models.CharField(max_length=6)),
                ('order', models.PositiveIntegerField(default=0)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='titles', to='player.Player')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
