# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-26 15:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0007_tenhounickname_is_main'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenhounickname',
            name='month_average_place',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='tenhounickname',
            name='month_played_games',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tenhoustatistics',
            name='stat_type',
            field=models.PositiveSmallIntegerField(choices=[[0, 'All time'], [1, 'Current month']], default=0),
        ),
    ]
