# Generated by Django 2.2.6 on 2019-12-18 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0007_playertitle'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='playertitle',
            options={'ordering': ['order']},
        ),
        migrations.RemoveField(
            model_name='playertitle',
            name='color',
        ),
        migrations.AddField(
            model_name='playertitle',
            name='background_color',
            field=models.CharField(default='', max_length=7),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='playertitle',
            name='text_color',
            field=models.CharField(default='1', max_length=7),
            preserve_default=False,
        ),
    ]
