# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-05-03 03:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0009_tenhounickname_four_games_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenhouGameLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash', models.CharField(max_length=40, unique=True)),
                ('delta', models.SmallIntegerField()),
                ('tenhou_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_logs', to='player.TenhouNickname')),
            ],
        ),
    ]
