# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-05-05 13:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0009_tenhounickname_four_games_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectedYakuman',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('log_id', models.CharField(max_length=44)),
                ('yakuman_list', models.CharField(max_length=60)),
                ('tenhou_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yakumans', to='player.TenhouNickname')),
            ],
        ),
    ]
