# -*- coding: utf-8 -*-

# Generated by Django 2.2.10 on 2020-02-22 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0010_playerquotaevent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playerwrc',
            name='player',
        ),
        migrations.DeleteModel(
            name='PlayerERMC',
        ),
        migrations.DeleteModel(
            name='PlayerWRC',
        ),
    ]
