# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-05-04 16:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0010_tenhougamelog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenhougamelog',
            name='hash',
        ),
        migrations.AddField(
            model_name='tenhougamelog',
            name='game_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tenhougamelog',
            name='lobby',
            field=models.PositiveSmallIntegerField(choices=[[0, 'Kyu lobby'], [1, 'Dan lobby'], [2, 'Upperdan lobby'], [3, 'Phoenix lobby']], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tenhougamelog',
            name='place',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tenhougamelog',
            name='delta',
            field=models.SmallIntegerField(default=0),
        ),
    ]
