# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-05-04 16:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0011_auto_20180504_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenhougamelog',
            name='game_rules',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='tenhougamelog',
            unique_together=set([('tenhou_object', 'game_date')]),
        ),
    ]
