# Generated by Django 4.2.9 on 2024-04-05 22:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("player", "0013_playertitle_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="player",
            name="pantheon_id",
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
    ]
