# Generated by Django 4.2.16 on 2024-09-10 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("player", "0014_alter_player_pantheon_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="is_exclude_from_rating",
            field=models.BooleanField(default=False),
        ),
    ]
