# Generated by Django 4.2.16 on 2025-02-02 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("player", "0015_player_is_exclude_from_rating"),
    ]

    operations = [
        migrations.AlterField(
            model_name="playerquotaevent",
            name="type",
            field=models.PositiveSmallIntegerField(choices=[[0, "ERMC 2019"], [1, "WRC 2020"], [2, "WRC 2025"]]),
        ),
    ]
