# Generated by Django 5.2 on 2025-05-08 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("player", "0016_alter_playerquotaevent_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="playertitle",
            name="is_hide",
            field=models.BooleanField(default=False),
        ),
    ]
