# Generated by Django 5.2.7 on 2025-10-17 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("player", "0017_playertitle_is_hide"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="is_hide_ms_activity",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="player",
            name="is_hide_tenhou_activity",
            field=models.BooleanField(default=False),
        ),
    ]
