# -*- coding: utf-8 -*-
# Generated by https://github.com/verloop/twirpy/protoc-gen-twirpy.  DO NOT EDIT!
# source: frey.proto

from google.protobuf import symbol_database as _symbol_database
from twirp.base import Endpoint
from twirp.client import TwirpClient
from twirp.server import TwirpServer

_sym_db = _symbol_database.Default()


class FreyServer(TwirpServer):

    def __init__(self, *args, service, server_path_prefix="/twirp"):
        super().__init__(service=service)
        self._prefix = f"{server_path_prefix}/common.Frey"
        self._endpoints = {
            "RequestRegistration": Endpoint(
                service_name="Frey",
                name="RequestRegistration",
                function=getattr(service, "RequestRegistration"),
                input=_sym_db.GetSymbol("common.AuthRequestRegistrationPayload"),
                output=_sym_db.GetSymbol("common.AuthRequestRegistrationResponse"),
            ),
            "ApproveRegistration": Endpoint(
                service_name="Frey",
                name="ApproveRegistration",
                function=getattr(service, "ApproveRegistration"),
                input=_sym_db.GetSymbol("common.AuthApproveRegistrationPayload"),
                output=_sym_db.GetSymbol("common.AuthApproveRegistrationResponse"),
            ),
            "Authorize": Endpoint(
                service_name="Frey",
                name="Authorize",
                function=getattr(service, "Authorize"),
                input=_sym_db.GetSymbol("common.AuthAuthorizePayload"),
                output=_sym_db.GetSymbol("common.AuthAuthorizeResponse"),
            ),
            "QuickAuthorize": Endpoint(
                service_name="Frey",
                name="QuickAuthorize",
                function=getattr(service, "QuickAuthorize"),
                input=_sym_db.GetSymbol("common.AuthQuickAuthorizePayload"),
                output=_sym_db.GetSymbol("common.AuthQuickAuthorizeResponse"),
            ),
            "Me": Endpoint(
                service_name="Frey",
                name="Me",
                function=getattr(service, "Me"),
                input=_sym_db.GetSymbol("common.AuthMePayload"),
                output=_sym_db.GetSymbol("common.AuthMeResponse"),
            ),
            "DepersonalizeAccount": Endpoint(
                service_name="Frey",
                name="DepersonalizeAccount",
                function=getattr(service, "DepersonalizeAccount"),
                input=_sym_db.GetSymbol("common.DepersonalizePayload"),
                output=_sym_db.GetSymbol("common.GenericSuccessResponse"),
            ),
            "ChangePassword": Endpoint(
                service_name="Frey",
                name="ChangePassword",
                function=getattr(service, "ChangePassword"),
                input=_sym_db.GetSymbol("common.AuthChangePasswordPayload"),
                output=_sym_db.GetSymbol("common.AuthChangePasswordResponse"),
            ),
            "RequestResetPassword": Endpoint(
                service_name="Frey",
                name="RequestResetPassword",
                function=getattr(service, "RequestResetPassword"),
                input=_sym_db.GetSymbol("common.AuthRequestResetPasswordPayload"),
                output=_sym_db.GetSymbol("common.AuthRequestResetPasswordResponse"),
            ),
            "ApproveResetPassword": Endpoint(
                service_name="Frey",
                name="ApproveResetPassword",
                function=getattr(service, "ApproveResetPassword"),
                input=_sym_db.GetSymbol("common.AuthApproveResetPasswordPayload"),
                output=_sym_db.GetSymbol("common.AuthApproveResetPasswordResponse"),
            ),
            "UpdatePersonalInfo": Endpoint(
                service_name="Frey",
                name="UpdatePersonalInfo",
                function=getattr(service, "UpdatePersonalInfo"),
                input=_sym_db.GetSymbol("common.PersonsUpdatePersonalInfoPayload"),
                output=_sym_db.GetSymbol("common.GenericSuccessResponse"),
            ),
            "GetPersonalInfo": Endpoint(
                service_name="Frey",
                name="GetPersonalInfo",
                function=getattr(service, "GetPersonalInfo"),
                input=_sym_db.GetSymbol("common.PersonsGetPersonalInfoPayload"),
                output=_sym_db.GetSymbol("common.PersonsGetPersonalInfoResponse"),
            ),
            "FindByTenhouIds": Endpoint(
                service_name="Frey",
                name="FindByTenhouIds",
                function=getattr(service, "FindByTenhouIds"),
                input=_sym_db.GetSymbol("common.PersonsFindByTenhouIdsPayload"),
                output=_sym_db.GetSymbol("common.PersonsFindByTenhouIdsResponse"),
            ),
            "FindByMajsoulAccountId": Endpoint(
                service_name="Frey",
                name="FindByMajsoulAccountId",
                function=getattr(service, "FindByMajsoulAccountId"),
                input=_sym_db.GetSymbol("common.PersonsFindByMajsoulIdsPayload"),
                output=_sym_db.GetSymbol("common.PersonsFindByTenhouIdsResponse"),
            ),
            "FindByTitle": Endpoint(
                service_name="Frey",
                name="FindByTitle",
                function=getattr(service, "FindByTitle"),
                input=_sym_db.GetSymbol("common.PersonsFindByTitlePayload"),
                output=_sym_db.GetSymbol("common.PersonsFindByTitleResponse"),
            ),
            "GetEventAdmins": Endpoint(
                service_name="Frey",
                name="GetEventAdmins",
                function=getattr(service, "GetEventAdmins"),
                input=_sym_db.GetSymbol("common.AccessGetEventAdminsPayload"),
                output=_sym_db.GetSymbol("common.AccessGetEventAdminsResponse"),
            ),
            "GetEventReferees": Endpoint(
                service_name="Frey",
                name="GetEventReferees",
                function=getattr(service, "GetEventReferees"),
                input=_sym_db.GetSymbol("common.AccessGetEventRefereesPayload"),
                output=_sym_db.GetSymbol("common.AccessGetEventRefereesResponse"),
            ),
            "GetMajsoulNicknames": Endpoint(
                service_name="Frey",
                name="GetMajsoulNicknames",
                function=getattr(service, "GetMajsoulNicknames"),
                input=_sym_db.GetSymbol("common.PersonsGetMajsoulNicknamesPayload"),
                output=_sym_db.GetSymbol("common.PersonsGetMajsoulNicknamesResponse"),
            ),
            "GetSuperadminFlag": Endpoint(
                service_name="Frey",
                name="GetSuperadminFlag",
                function=getattr(service, "GetSuperadminFlag"),
                input=_sym_db.GetSymbol("common.AccessGetSuperadminFlagPayload"),
                output=_sym_db.GetSymbol("common.AccessGetSuperadminFlagResponse"),
            ),
            "GetOwnedEventIds": Endpoint(
                service_name="Frey",
                name="GetOwnedEventIds",
                function=getattr(service, "GetOwnedEventIds"),
                input=_sym_db.GetSymbol("common.AccessGetOwnedEventIdsPayload"),
                output=_sym_db.GetSymbol("common.AccessGetOwnedEventIdsResponse"),
            ),
            "AddRuleForPerson": Endpoint(
                service_name="Frey",
                name="AddRuleForPerson",
                function=getattr(service, "AddRuleForPerson"),
                input=_sym_db.GetSymbol("common.AccessAddRuleForPersonPayload"),
                output=_sym_db.GetSymbol("common.AccessAddRuleForPersonResponse"),
            ),
            "DeleteRuleForPerson": Endpoint(
                service_name="Frey",
                name="DeleteRuleForPerson",
                function=getattr(service, "DeleteRuleForPerson"),
                input=_sym_db.GetSymbol("common.AccessDeleteRuleForPersonPayload"),
                output=_sym_db.GetSymbol("common.GenericSuccessResponse"),
            ),
            "CreateAccount": Endpoint(
                service_name="Frey",
                name="CreateAccount",
                function=getattr(service, "CreateAccount"),
                input=_sym_db.GetSymbol("common.PersonsCreateAccountPayload"),
                output=_sym_db.GetSymbol("common.PersonsCreateAccountResponse"),
            ),
            "GetNotificationsSettings": Endpoint(
                service_name="Frey",
                name="GetNotificationsSettings",
                function=getattr(service, "GetNotificationsSettings"),
                input=_sym_db.GetSymbol("common.PersonsGetNotificationsSettingsPayload"),
                output=_sym_db.GetSymbol("common.PersonsGetNotificationsSettingsResponse"),
            ),
            "SetNotificationsSettings": Endpoint(
                service_name="Frey",
                name="SetNotificationsSettings",
                function=getattr(service, "SetNotificationsSettings"),
                input=_sym_db.GetSymbol("common.PersonsSetNotificationsSettingsPayload"),
                output=_sym_db.GetSymbol("common.GenericSuccessResponse"),
            ),
        }


class FreyClient(TwirpClient):

    def RequestRegistration(self, *args, ctx, request, server_path_prefix="/twirp", **kwargs):
        return self._make_request(
            url=f"{server_path_prefix}/common.Frey/RequestRegistration",
            ctx=ctx,
            request=request,
            response_obj=_sym_db.GetSymbol("common.AuthRequestRegistrationResponse"),
            **kwargs,
        )

    def ApproveRegistration(self, *args, ctx, request, server_path_prefix="/twirp", **kwargs):
        return self._make_request(
            url=f"{server_path_prefix}/common.Frey/ApproveRegistration",
            ctx=ctx,
            request=request,
            response_obj=_sym_db.GetSymbol("common.AuthApproveRegistrationResponse"),
            **kwargs,
        )

    def Authorize(self, *args, ctx, request, server_path_prefix="/twirp", **kwargs):
        return self._make_request(
            url=f"{server_path_prefix}/common.Frey/Authorize",
            ctx=ctx,
            request=request,
            response_obj=_sym_db.GetSymbol("common.AuthAuthorizeResponse"),
            **kwargs,
        )

    def QuickAuthorize(self, *args, ctx, request, server_path_prefix="/twirp", **kwargs):
        return self._make_request(
            url=f"{server_path_prefix}/common.Frey/QuickAuthorize",
            ctx=ctx,
            request=request,
            response_obj=_sym_db.GetSymbol("common.AuthQuickAuthorizeResponse"),
            **kwargs,
        )

    def Me(self, *args, ctx, request, server_path_prefix="/twirp", **kwargs):
        return self._make_request(
            url=f"{server_path_prefix}/common.Frey/Me",
            ctx=ctx,
            request=request,
            response_obj=_sym_db.GetSymbol("common.AuthMeResponse"),
            **kwargs,
        )

    def DepersonalizeAccount(self, *args, ctx, request, server_path_prefix="/twirp", **kwargs):
        return self._make_request(
            url=f"{server_path_prefix}/common.Frey/DepersonalizeAccount",
            ctx=ctx,
            request=request,
            response_obj=_sym_db.GetSymbol("common.GenericSuccessResponse"),
            **kwargs,
        )

    def ChangePassword(self, *args, ctx, request, server_path_prefix="/twirp", **kwargs):
        return self._make_request(
            url=f"{server_path_prefix}/common.Frey/ChangePassword",
            ctx=ctx,
            request=request,
            response_obj=_sym_db.GetSymbol("common.AuthChangePasswordResponse"),
            **kwargs,
        )

    def RequestResetPassword(self, *args, ctx, request, server_path_prefix="/twirp", **kwargs):
        return self._make_request(
            url=f"{server_path_prefix}/common.Frey/RequestResetPassword",
            ctx=ctx,
            request=request,
            response_obj=_sym_db.GetSymbol("common.AuthRequestResetPasswordResponse"),
            **kwargs,
        )

    def ApproveResetPassword(self, *args, ctx, request, server_path_prefix="/twirp", **kwargs):
        return self._make_request(
            url=f"{server_path_prefix}/common.Frey/ApproveResetPassword",
            ctx=ctx,
            request=request,
            response_obj=_sym_db.GetSymbol("common.AuthApproveResetPasswordResponse"),
            **kwargs,
        )

    def UpdatePersonalInfo(self, *args, ctx, request, server_path_prefix="/twirp", **kwargs):
        return self._make_request(
            url=f"{server_path_prefix}/common.Frey/UpdatePersonalInfo",
            ctx=ctx,
            request=request,
            response_obj=_sym_db.GetSymbol("common.GenericSuccessResponse"),
            **kwargs,
        )

    def GetPersonalInfo(self, *args, ctx, request, server_path_prefix="/twirp", **kwargs):
        return self._make_request(
            url=f"{server_path_prefix}/common.Frey/GetPersonalInfo",
            ctx=ctx,
            request=request,
            response_obj=_sym_db.GetSymbol("common.PersonsGetPersonalInfoResponse"),
            **kwargs,
        )

    def FindByTenhouIds(self, *args, ctx, request, server_path_prefix="/twirp", **kwargs):
        return self._make_request(
            url=f"{server_path_prefix}/common.Frey/FindByTenhouIds",
            ctx=ctx,
            request=request,
            response_obj=_sym_db.GetSymbol("common.PersonsFindByTenhouIdsResponse"),
            **kwargs,
        )

    def FindByMajsoulAccountId(self, *args, ctx, request, server_path_prefix="/twirp", **kwargs):
        return self._make_request(
            url=f"{server_path_prefix}/common.Frey/FindByMajsoulAccountId",
            ctx=ctx,
            request=request,
            response_obj=_sym_db.GetSymbol("common.PersonsFindByTenhouIdsResponse"),
            **kwargs,
        )

    def FindByTitle(self, *args, ctx, request, server_path_prefix="/twirp", **kwargs):
        return self._make_request(
            url=f"{server_path_prefix}/common.Frey/FindByTitle",
            ctx=ctx,
            request=request,
            response_obj=_sym_db.GetSymbol("common.PersonsFindByTitleResponse"),
            **kwargs,
        )

    def GetEventAdmins(self, *args, ctx, request, server_path_prefix="/twirp", **kwargs):
        return self._make_request(
            url=f"{server_path_prefix}/common.Frey/GetEventAdmins",
            ctx=ctx,
            request=request,
            response_obj=_sym_db.GetSymbol("common.AccessGetEventAdminsResponse"),
            **kwargs,
        )

    def GetEventReferees(self, *args, ctx, request, server_path_prefix="/twirp", **kwargs):
        return self._make_request(
            url=f"{server_path_prefix}/common.Frey/GetEventReferees",
            ctx=ctx,
            request=request,
            response_obj=_sym_db.GetSymbol("common.AccessGetEventRefereesResponse"),
            **kwargs,
        )

    def GetMajsoulNicknames(self, *args, ctx, request, server_path_prefix="/twirp", **kwargs):
        return self._make_request(
            url=f"{server_path_prefix}/common.Frey/GetMajsoulNicknames",
            ctx=ctx,
            request=request,
            response_obj=_sym_db.GetSymbol("common.PersonsGetMajsoulNicknamesResponse"),
            **kwargs,
        )

    def GetSuperadminFlag(self, *args, ctx, request, server_path_prefix="/twirp", **kwargs):
        return self._make_request(
            url=f"{server_path_prefix}/common.Frey/GetSuperadminFlag",
            ctx=ctx,
            request=request,
            response_obj=_sym_db.GetSymbol("common.AccessGetSuperadminFlagResponse"),
            **kwargs,
        )

    def GetOwnedEventIds(self, *args, ctx, request, server_path_prefix="/twirp", **kwargs):
        return self._make_request(
            url=f"{server_path_prefix}/common.Frey/GetOwnedEventIds",
            ctx=ctx,
            request=request,
            response_obj=_sym_db.GetSymbol("common.AccessGetOwnedEventIdsResponse"),
            **kwargs,
        )

    def AddRuleForPerson(self, *args, ctx, request, server_path_prefix="/twirp", **kwargs):
        return self._make_request(
            url=f"{server_path_prefix}/common.Frey/AddRuleForPerson",
            ctx=ctx,
            request=request,
            response_obj=_sym_db.GetSymbol("common.AccessAddRuleForPersonResponse"),
            **kwargs,
        )

    def DeleteRuleForPerson(self, *args, ctx, request, server_path_prefix="/twirp", **kwargs):
        return self._make_request(
            url=f"{server_path_prefix}/common.Frey/DeleteRuleForPerson",
            ctx=ctx,
            request=request,
            response_obj=_sym_db.GetSymbol("common.GenericSuccessResponse"),
            **kwargs,
        )

    def CreateAccount(self, *args, ctx, request, server_path_prefix="/twirp", **kwargs):
        return self._make_request(
            url=f"{server_path_prefix}/common.Frey/CreateAccount",
            ctx=ctx,
            request=request,
            response_obj=_sym_db.GetSymbol("common.PersonsCreateAccountResponse"),
            **kwargs,
        )

    def GetNotificationsSettings(self, *args, ctx, request, server_path_prefix="/twirp", **kwargs):
        return self._make_request(
            url=f"{server_path_prefix}/common.Frey/GetNotificationsSettings",
            ctx=ctx,
            request=request,
            response_obj=_sym_db.GetSymbol("common.PersonsGetNotificationsSettingsResponse"),
            **kwargs,
        )

    def SetNotificationsSettings(self, *args, ctx, request, server_path_prefix="/twirp", **kwargs):
        return self._make_request(
            url=f"{server_path_prefix}/common.Frey/SetNotificationsSettings",
            ctx=ctx,
            request=request,
            response_obj=_sym_db.GetSymbol("common.GenericSuccessResponse"),
            **kwargs,
        )
