# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-23 05:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournamentplayers',
            name='telegram_username',
            field=models.CharField(max_length=32),
        ),
    ]
