# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-23 14:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online', '0002_auto_20180123_0509'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournamentgame',
            name='log_link',
        ),
        migrations.AddField(
            model_name='tournamentgame',
            name='log_id',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
