# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-24 08:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online', '0003_auto_20180123_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentstatus',
            name='end_break_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
