# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-01 12:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online', '0005_auto_20180128_1217'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentplayers',
            name='pantheon_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
