# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-10 02:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online', '0006_tournamentplayers_pantheon_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentstatus',
            name='registration_closed',
            field=models.BooleanField(default=False),
        ),
    ]
