# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-12 15:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('online', '0008_auto_20180210_0548'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tournamentgame',
            options={'ordering': ['-tournament', '-tournament_round', 'status']},
        ),
    ]
