# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-01-12 17:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online', '0009_auto_20180412_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentplayers',
            name='added_to_pantheon',
            field=models.BooleanField(default=False),
        ),
    ]
