# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-01-14 14:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online', '0010_tournamentplayers_added_to_pantheon'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentplayers',
            name='enabled_in_pantheon',
            field=models.BooleanField(default=True),
        ),
    ]
