# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-02-16 16:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online', '0012_remove_tournamentgameplayer_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentplayers',
            name='team_name',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='tournamentplayers',
            name='team_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
