# -*- coding: utf-8 -*-

# Generated by Django 2.2.10 on 2020-05-09 15:41

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0027_auto_20191218_1249'),
        ('online', '0013_auto_20190216_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentplayers',
            name='discord_username',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='tournamentplayers',
            name='telegram_username',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.CreateModel(
            name='TournamentNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('notification_type', models.CharField(choices=[['game_started', 'game_started'], ['game_failed', 'game_failed'], ['game_failed_no_members', 'game_failed_no_members'], ['game_ended', 'game_ended'], ['confirmation_started', 'confirmation_started'], ['confirmation_ended', 'confirmation_ended'], ['games_prepared', 'games_prepared'], ['round_finished', 'round_finished'], ['tournament_finished', 'tournament_finished']], max_length=300)),
                ('message_kwargs', django.contrib.postgres.fields.jsonb.JSONField(blank=True)),
                ('destination', models.PositiveSmallIntegerField(choices=[[0, 'Telegram'], [1, 'Discord']])),
                ('is_processed', models.BooleanField(default=False)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournament.Tournament')),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
    ]
