# Generated by Django 2.2.10 on 2020-05-10 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online', '0014_auto_20200509_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentnotification',
            name='failed',
            field=models.BooleanField(default=False),
        ),
    ]
