# Generated by Django 3.0.7 on 2020-12-20 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online', '0015_tournamentnotification_failed'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentplayers',
            name='is_replacement',
            field=models.BooleanField(default=False),
        ),
    ]
