# Generated by Django 3.2 on 2021-04-10 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online', '0018_auto_20210410_0502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournamentnotification',
            name='message_kwargs',
            field=models.JSONField(blank=True),
        ),
    ]
