# Generated by Django 4.2.2 on 2024-01-05 21:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("online", "0019_alter_tournamentnotification_message_kwargs"),
    ]

    operations = [
        migrations.AddField(
            model_name="tournamentplayers",
            name="ms_username",
            field=models.CharField(blank=True, null=True),
        ),
    ]
