# Generated by Django 4.2.2 on 2024-01-06 09:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("online", "0020_tournamentplayers_ms_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tournamentplayers",
            name="ms_username",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="tournamentplayers",
            name="tenhou_username",
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
