# Generated by Django 4.2.2 on 2024-01-06 10:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("online", "0022_tournamentplayers_ms_account_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tournamentplayers",
            name="ms_account_id",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
