# Generated by Django 4.2.9 on 2024-04-05 22:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tournament", "0043_tournament_is_apply_in_rating"),
        ("online", "0025_tournamentplayers_is_disable"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="tournamentplayers",
            unique_together={("tournament", "pantheon_id")},
        ),
    ]
