# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-12 14:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0001_initial'),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='managed_tournaments',
            field=models.ManyToManyField(blank=True, to='tournament.Tournament'),
        ),
    ]
