# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-12 14:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user_managed_tournaments'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_tournament_manager',
            field=models.BooleanField(default=False),
        ),
    ]
