# Generated by Django 3.2 on 2021-04-14 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20210413_2356'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachingplayerrequest',
            name='contacts',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
