# -*- coding: utf-8 -*-

# Generated by Django 3.2 on 2021-04-14 02:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0012_auto_20210410_0502'),
        ('account', '0008_attachingplayerrequest_contacts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachingplayerrequest',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attaching_request', to='player.player'),
        ),
    ]
