# Generated by Django 3.2.10 on 2022-02-10 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_alter_attachingplayerrequest_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='new_pantheon_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
