# -*- coding: utf-8 -*-

# Generated by Django 3.2.12 on 2022-02-23 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_user_new_pantheon_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_league_manager',
            field=models.BooleanField(default=False),
        ),
    ]
