# -*- coding: utf-8 -*-

# Generated by Django 4.2.2 on 2023-07-03 08:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0011_user_is_league_manager"),
    ]

    operations = [
        migrations.CreateModel(
            name="PantheonInfoUpdateLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("pantheon_id", models.PositiveIntegerField(blank=True, help_text="ID from NEW pantheon", null=True)),
                ("updated_information", models.JSONField(default=dict)),
                ("is_applied", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
