# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-15 17:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('player', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField()),
                ('type', models.PositiveSmallIntegerField(choices=[[0, 'Inner'], [1, 'EMA']])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RatingDelta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('delta', models.IntegerField()),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rating_delta', to='player.Player')),
                ('rating', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rating.Rating')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
