# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-29 03:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0005_auto_20171229_0323'),
        ('rating', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RatingResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('score', models.IntegerField(blank=True, default=None, null=True)),
                ('place', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rating_results', to='player.Player')),
                ('rating', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rating.Rating')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='ratingdelta',
            name='rating_place_after',
        ),
        migrations.RemoveField(
            model_name='ratingdelta',
            name='rating_place_before',
        ),
    ]
