# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-11 13:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[[0, 'RR'], [2, 'CRR'], [1, 'EMA'], [3, 'ONLINE']]),
        ),
    ]
