# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-16 07:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='name_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='rating',
            name='name_ru',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
