# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-30 03:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0002_auto_20171229_0323'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='description',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='rating',
            name='description_en',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='rating',
            name='description_ru',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
