# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-08-01 01:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0002_auto_20180211_1340'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratingdelta',
            name='date',
            field=models.DateField(blank=True, db_index=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='ratingdelta',
            name='is_last',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ratingresult',
            name='date',
            field=models.DateField(blank=True, db_index=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='ratingresult',
            name='is_last',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='tournamentcoefficients',
            name='date',
            field=models.DateField(blank=True, db_index=True, default=None, null=True),
        ),
    ]
