# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-17 12:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0002_ratingdelta_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratingdelta',
            name='rating_place_after',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ratingdelta',
            name='rating_place_before',
            field=models.PositiveSmallIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='ratingdelta',
            name='tournament_place',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
