# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-09-06 20:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0003_auto_20180801_0110'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentcoefficients',
            name='previous_age',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
