# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-31 01:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0003_auto_20171230_0333'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rating',
            options={'ordering': ['id']},
        ),
    ]
