# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-17 12:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0003_auto_20171217_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratingdelta',
            name='rating_place_before',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
