# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-04 07:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0005_auto_20180103_0554'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ratingdelta',
            name='players_coefficient',
        ),
        migrations.RemoveField(
            model_name='ratingdelta',
            name='sessions_coefficient',
        ),
        migrations.RemoveField(
            model_name='ratingdelta',
            name='tournament_age',
        ),
        migrations.RemoveField(
            model_name='ratingdelta',
            name='tournament_coefficient',
        ),
        migrations.AddField(
            model_name='ratingresult',
            name='rating_calculation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
