# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-04 10:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0009_auto_20180104_1032'),
        ('rating', '0006_auto_20180104_0748'),
    ]

    operations = [
        migrations.CreateModel(
            name='TournamentCoefficients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('coefficient', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('age', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('rating', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rating.Rating')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rating_results', to='tournament.Tournament')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
