# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-05 03:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0007_tournamentcoefficients'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='rating',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[[0, 'RR'], [2, 'CRR'], [1, 'EMA']]),
        ),
    ]
