# Generated by Django 4.2.16 on 2024-12-05 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tournament", "0051_alter_tournament_is_command"),
        ("rating", "0007_auto_20210410_0502"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExternalRating",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(unique=True)),
                ("description", models.TextField(blank=True, default="", null=True)),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="ExternalRatingTournament",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("rating", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="rating.externalrating")),
                (
                    "tournament",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="external_rating_delta",
                        to="tournament.tournament",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
