# Generated by Django 4.2.16 on 2024-12-06 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("player", "0015_player_is_exclude_from_rating"),
        ("rating", "0008_externalrating_externalratingtournament"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExternalRatingDelta",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=False)),
                ("date", models.DateField(blank=True, db_index=True, default=None, null=True)),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="external_rating_delta",
                        to="player.player",
                    ),
                ),
                ("rating", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="rating.externalrating")),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
