# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-05 04:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0008_auto_20180105_0329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournamentcoefficients',
            name='rating',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rating.Rating'),
        ),
        migrations.AlterField(
            model_name='tournamentcoefficients',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating_results', to='tournament.Tournament'),
        ),
    ]
