# Generated by Django 4.2.16 on 2024-12-06 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rating", "0009_externalratingdelta"),
    ]

    operations = [
        migrations.AddField(
            model_name="externalratingdelta",
            name="base_rank",
            field=models.FloatField(default=0.0),
        ),
    ]
