# Generated by Django 4.2.16 on 2024-12-06 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rating", "0011_alter_externalratingdelta_rating_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="externalratingdelta",
            name="place",
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
    ]
