# Generated by Django 4.2.16 on 2024-12-08 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("rating", "0012_externalratingdelta_place"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExternalRatingDate",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("date", models.DateField(db_index=True)),
                ("rating", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="rating.externalrating")),
            ],
            options={
                "ordering": ["-date"],
            },
        ),
    ]
