# Generated by Django 4.2.16 on 2024-12-08 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rating", "0013_externalratingdate"),
    ]

    operations = [
        migrations.AddField(
            model_name="externalrating",
            name="is_hidden",
            field=models.BooleanField(default=False),
        ),
    ]
