# Generated by Django 4.2.16 on 2024-12-08 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rating", "0015_alter_externalrating_is_hidden"),
    ]

    operations = [
        migrations.AddField(
            model_name="externalrating",
            name="description_en",
            field=models.TextField(blank=True, default="", null=True),
        ),
        migrations.AddField(
            model_name="externalrating",
            name="description_ru",
            field=models.TextField(blank=True, default="", null=True),
        ),
        migrations.AddField(
            model_name="externalrating",
            name="name_en",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="externalrating",
            name="name_ru",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
