# Generated by Django 4.2.16 on 2024-12-13 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rating", "0016_externalrating_description_en_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="externalratingdelta",
            name="tournament_numbers",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
