# Generated by Django 4.2.16 on 2024-12-13 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rating", "0017_externalratingdelta_tournament_numbers"),
    ]

    operations = [
        migrations.AddField(
            model_name="externalratingdelta",
            name="last_game_date",
            field=models.DateField(blank=True, db_index=True, default=None, null=True),
        ),
    ]
