# Generated by Django 4.2.16 on 2024-12-18 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rating", "0018_externalratingdelta_last_game_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="externalrating",
            name="type",
            field=models.PositiveSmallIntegerField(
                blank=True, choices=[[0, "TRUESKILL"], [1, "ONLINE_TRUESKILL"]], null=True
            ),
        ),
    ]
