# Generated by Django 4.2.16 on 2024-12-24 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rating", "0019_externalrating_type"),
    ]

    operations = [
        migrations.RenameField(
            model_name="externalratingdelta",
            old_name="tournament_numbers",
            new_name="game_numbers",
        ),
    ]
