# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-06-29 04:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('player', '0002_player_pantheon_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenhouNickname',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('tenhou_username', models.CharField(max_length=8)),
                ('username_created_at', models.DateField()),
                ('rank', models.PositiveSmallIntegerField(choices=[[0, '新人'], [1, '９級'], [2, '８級'], [3, '７級'], [4, '６級'], [5, '５級'], [6, '４級'], [7, '３級'], [8, '２級'], [9, '１級'], [10, '初段'], [11, '二段'], [12, '三段'], [13, '四段'], [14, '五段'], [15, '六段'], [16, '七段'], [17, '八段'], [18, '九段'], [19, '十段'], [20, '天鳳位']])),
                ('average_place', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('played_games', models.PositiveIntegerField(default=0)),
                ('month_average_place', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('month_played_games', models.PositiveIntegerField(default=0)),
                ('four_games_rate', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('latest_twenty_places', models.CharField(blank=True, max_length=40, null=True)),
                ('pt', models.PositiveSmallIntegerField(default=0)),
                ('end_pt', models.PositiveSmallIntegerField(default=0)),
                ('last_played_date', models.DateField(blank=True, null=True)),
                ('is_main', models.BooleanField(default=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenhou', to='player.Player')),
            ],
            options={
                'db_table': 'player_tenhounickname',
                'ordering': ['-rank'],
            },
        ),
    ]
