# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-03-28 09:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenhou', '0006_auto_20190328_0856'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tenhouaggregatedstatistics',
            old_name='game_type',
            new_name='game_players',
        ),
    ]
