# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-03-28 09:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenhou', '0007_auto_20190328_0901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenhouaggregatedstatistics',
            name='rank',
            field=models.PositiveSmallIntegerField(blank=True, choices=[[0, '新人'], [1, '９級'], [2, '８級'], [3, '７級'], [4, '６級'], [5, '５級'], [6, '４級'], [7, '３級'], [8, '２級'], [9, '１級'], [10, '初段'], [11, '二段'], [12, '三段'], [13, '四段'], [14, '五段'], [15, '六段'], [16, '七段'], [17, '八段'], [18, '九段'], [19, '十段'], [20, '天鳳位']], null=True),
        ),
    ]
