# Generated by Django 3.2.15 on 2022-09-03 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenhou', '0008_auto_20210410_0502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenhougamelog',
            name='lobby',
            field=models.PositiveSmallIntegerField(choices=[[0, 'Ippan'], [1, 'Joukyuu'], [2, 'Tokujou'], [3, 'Houou']]),
        ),
        migrations.AlterField(
            model_name='tenhoustatistics',
            name='lobby',
            field=models.PositiveSmallIntegerField(choices=[[0, 'Ippan'], [1, 'Joukyuu'], [2, 'Tokujou'], [3, 'Houou']]),
        ),
    ]
