# Generated by Django 5.2.6 on 2025-10-05 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenhou", "0009_auto_20220903_0454"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tenhounickname",
            name="tenhou_username",
            field=models.CharField(db_index=True, max_length=8),
        ),
    ]
