# Generated by Django 5.2.7 on 2025-10-07 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenhou", "0010_alter_tenhounickname_tenhou_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenhounickname",
            name="last_recalculated_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
