# -*- coding: utf-8 -*-

# Generated by Django 3.2.10 on 2022-02-02 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0002_leagueplayer_leagueteam'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='games',
            field=models.SmallIntegerField(null=True),
        ),
    ]
