# -*- coding: utf-8 -*-

# Generated by Django 3.2.10 on 2022-02-02 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0003_league_games'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leagueteam',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='leagueteam',
            name='number',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
