# -*- coding: utf-8 -*-

# Generated by Django 3.2.10 on 2022-02-03 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0004_auto_20220202_0929'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leagueplayer',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='leagueteam',
            options={'ordering': ['number']},
        ),
        migrations.AddField(
            model_name='leagueplayer',
            name='tenhou_nickname',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='league',
            name='games',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='leagueteam',
            name='number',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
