# -*- coding: utf-8 -*-

# Generated by Django 3.2.10 on 2022-02-06 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0007_auto_20220206_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaguesession',
            name='league',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='league.league'),
            preserve_default=False,
        ),
    ]
