# Generated by Django 3.2.10 on 2022-02-06 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0008_leaguesession_league'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leaguegameplayer',
            options={'ordering': ['position']},
        ),
        migrations.AddField(
            model_name='leaguegameplayer',
            name='player_pantheon_id',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='leaguegameplayer',
            name='team',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='games', to='league.leagueteam'),
            preserve_default=False,
        ),
    ]
