# Generated by Django 3.2.10 on 2022-02-06 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0010_alter_leaguegameplayer_player_pantheon_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaguegameplayer',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='players', to='league.leaguegame'),
        ),
    ]
