# -*- coding: utf-8 -*-

# Generated by Django 3.2.10 on 2022-02-10 05:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('league', '0011_alter_leaguegameplayer_game'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leagueplayer',
            name='pantheon_id',
        ),
        migrations.AddField(
            model_name='leagueplayer',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
