# -*- coding: utf-8 -*-

# Generated by Django 3.2.10 on 2022-02-10 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0014_rename_player_leaguegameplayer_assigned_player'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeagueGameSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField()),
                ('assigned_player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='games', to='league.leagueplayer')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.AlterModelOptions(
            name='leaguegame',
            options={'ordering': ['id']},
        ),
        migrations.DeleteModel(
            name='LeagueGamePlayer',
        ),
        migrations.AddField(
            model_name='leaguegameslot',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='slots', to='league.leaguegame'),
        ),
        migrations.AddField(
            model_name='leaguegameslot',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='games', to='league.leagueteam'),
        ),
    ]
