# Generated by Django 3.2.10 on 2022-02-11 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0015_auto_20220210_0551'),
    ]

    operations = [
        migrations.AddField(
            model_name='leagueplayer',
            name='is_captain',
            field=models.BooleanField(default=False),
        ),
    ]
