# -*- coding: utf-8 -*-

# Generated by Django 3.2.10 on 2022-02-11 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0016_leagueplayer_is_captain'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leagueplayer',
            options={'ordering': ['-is_captain', 'name']},
        ),
    ]
