# -*- coding: utf-8 -*-

# Generated by Django 3.2.15 on 2022-09-03 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0018_alter_leaguesession_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leaguegame',
            options={'ordering': ['-id']},
        ),
    ]
