# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-20 03:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('player', '0001_initial'),
        ('club', '0001_initial'),
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('name_en', models.CharField(max_length=255, null=True)),
                ('name_ru', models.CharField(max_length=255, null=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('date', models.DateField()),
                ('number_of_days', models.PositiveSmallIntegerField(default=0)),
                ('number_of_sessions', models.PositiveSmallIntegerField(default=0)),
                ('number_of_players', models.PositiveSmallIntegerField(default=0)),
                ('game_type', models.PositiveSmallIntegerField(choices=[[0, 'Riichi'], [1, 'MCR']], default=0)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='settings.City')),
                ('clubs', models.ManyToManyField(to='club.Club')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='settings.Country')),
                ('tournament_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='settings.TournamentType')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TournamentResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('place', models.PositiveSmallIntegerField()),
                ('scores', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tournament_results', to='player.Player')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='results', to='tournament.Tournament')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
