# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-13 04:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='registrations_pre_moderation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tournamentregistration',
            name='additional_contact',
            field=models.CharField(blank=True, default='', help_text='It will be visible only to the tournament administrator', max_length=255, null=True, verbose_name='Additional contact. Optional'),
        ),
    ]
