# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-13 12:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0002_auto_20180113_0437'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentregistration',
            name='is_approved',
            field=models.BooleanField(default=True),
        ),
    ]
