# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-26 02:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0002_tournament_is_enabled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='is_enabled',
        ),
        migrations.AddField(
            model_name='tournament',
            name='is_upcoming',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tournament',
            name='registration_description',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='registration_description_en',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='registration_description_ru',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='registration_link',
            field=models.URLField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='number_of_days',
            field=models.PositiveSmallIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='number_of_players',
            field=models.PositiveSmallIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='number_of_sessions',
            field=models.PositiveSmallIntegerField(blank=True, default=0),
        ),
    ]
