# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-26 02:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0003_auto_20171226_0232'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tournament',
            old_name='date',
            new_name='end_date',
        ),
    ]
