# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-16 08:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0003_tournament_number_of_players'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='slug',
            field=models.SlugField(default='test'),
            preserve_default=False,
        ),
    ]
