# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-28 04:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0004_auto_20171226_0234'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='ema_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
