# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-18 13:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0005_remove_tournament_tournament_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tournament',
            old_name='tournament_type_new',
            new_name='tournament_type',
        ),
    ]
