# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-04 07:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0006_auto_20171229_0120'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='tournament_age',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='tournament_coefficient',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
