# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-19 13:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0007_auto_20180118_1424'),
    ]

    operations = [
        migrations.CreateModel(
            name='TournamentApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('text', models.TextField(help_text='We would like to know tournament date, place and your contacts', verbose_name='Tell us about your tournament')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
