# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-04 09:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0007_auto_20180104_0748'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='need_qualification',
            field=models.BooleanField(default=False),
        ),
    ]
