# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-28 12:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0008_tournamentapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='fill_city_in_registration',
            field=models.BooleanField(default=True),
        ),
    ]
