# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-04 10:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0008_tournament_need_qualification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='tournament_age',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='tournament_coefficient',
        ),
    ]
