# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-05 03:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0009_auto_20180104_1032'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='has_accreditation',
            field=models.BooleanField(default=True),
        ),
    ]
