# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-29 03:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0009_tournament_fill_city_in_registration'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentregistration',
            name='allow_to_save_data',
            field=models.BooleanField(default=False, verbose_name='I allow to store my personal data'),
        ),
    ]
