# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-05 12:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0010_tournament_has_accreditation'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='pantheon_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
