# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-09 14:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0006_auto_20171231_0157'),
        ('settings', '0004_auto_20180105_0329'),
        ('tournament', '0011_tournament_pantheon_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='TournamentRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=255, verbose_name='First name')),
                ('last_name', models.CharField(max_length=255, verbose_name='Last name')),
                ('city', models.CharField(max_length=255, verbose_name='City')),
                ('phone', models.CharField(help_text='It will be visible only to the tournament administrator', max_length=255, verbose_name='Phone')),
                ('city_object', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='settings.City')),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tournament_registrations', to='player.Player')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='tournament',
            name='opened_registration',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tournamentregistration',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tournament_registrations', to='tournament.Tournament'),
        ),
    ]
