# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-10 02:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0011_onlinetournamentregistration_allow_to_save_data'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='onlinetournamentregistration',
            unique_together=set([('tenhou_nickname', 'tournament')]),
        ),
    ]
