# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-15 13:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0012_auto_20180210_0240'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='results_description',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='results_description_en',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='results_description_ru',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
