# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-18 13:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0014_auto_20180218_0502'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentresult',
            name='exclude_from_rating',
            field=models.BooleanField(default=False),
        ),
    ]
