# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-06-16 13:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0019_tournament_is_hidden'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='game_type',
        ),
    ]
