# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-07-23 03:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0020_remove_tournament_game_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentresult',
            name='games',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
