# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-08-01 01:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0021_tournamentresult_games'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='end_date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='tournament_type',
            field=models.CharField(choices=[['rr', 'rr'], ['crr', 'crr'], ['ema', 'ema'], ['fema', 'fema'], ['other', 'other'], ['online', 'online']], db_index=True, default='rr', max_length=10),
        ),
    ]
