# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-08-29 10:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0022_auto_20180801_0110'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentresult',
            name='player_string',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='tournamentresult',
            name='player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tournament_results', to='player.Player'),
        ),
    ]
