# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-12-29 15:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0025_onlinetournamentregistration_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='is_event',
            field=models.BooleanField(default=False),
        ),
    ]
