# -*- coding: utf-8 -*-

# Generated by Django 2.2.6 on 2019-12-18 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0026_tournament_is_event'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tournament',
            old_name='need_qualification',
            new_name='russian_cup',
        ),
        migrations.AlterField(
            model_name='tournament',
            name='tournament_type',
            field=models.CharField(choices=[['rr', 'rr'], ['crr', 'crr'], ['ema', 'ema'], ['fema', 'fema'], ['other', 'other'], ['online', 'online'], ['champ', 'champ.']], db_index=True, default='rr', max_length=10),
        ),
    ]
