# -*- coding: utf-8 -*-

# Generated by Django 3.0.7 on 2021-02-11 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0027_auto_20191218_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlinetournamentregistration',
            name='is_highlighted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='onlinetournamentregistration',
            name='notes',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Additional info'),
        ),
        migrations.AlterField(
            model_name='tournamentregistration',
            name='notes',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Additional info'),
        ),
    ]
