# -*- coding: utf-8 -*-

# Generated by Django 3.2 on 2021-05-19 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0029_auto_20210410_0502'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='is_majsoul_tournament',
            field=models.BooleanField(default=False),
        ),
    ]
