# -*- coding: utf-8 -*-

# Generated by Django 3.2.7 on 2021-11-17 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0030_tournament_is_majsoul_tournament'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournamentregistration',
            name='notes',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Team name'),
        ),
    ]
