# Generated by Django 3.2.18 on 2023-03-15 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0032_alter_onlinetournamentregistration_notes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tournament',
            old_name='pantheon_id',
            new_name='old_pantheon_id',
        ),
    ]
