# Generated by Django 4.2.2 on 2023-07-05 10:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tournament", "0034_tournament_new_pantheon_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="tournament",
            name="is_pantheon_registration",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="tournament",
            name="fill_city_in_registration",
            field=models.BooleanField(default=False),
        ),
    ]
