# Generated by Django 4.2.2 on 2023-07-05 12:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("tournament", "0035_tournament_is_pantheon_registration_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="onlinetournamentregistration",
            name="user",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="onlinetournamentregistration",
            name="last_name",
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="Last name"),
        ),
    ]
