# Generated by Django 4.2.2 on 2023-07-05 12:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tournament", "0036_onlinetournamentregistration_user_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="onlinetournamentregistration",
            name="tenhou_nickname",
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="Tenhou.net nickname"),
        ),
    ]
