# Generated by Django 4.2.2 on 2023-12-30 11:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tournament", "0038_ms_onlinetournamentregistration_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="msonlinetournamentregistration",
            name="notes",
            field=models.TextField(blank=True, default="", null=True, verbose_name="Additional info"),
        ),
    ]
