# Generated by Django 4.2.9 on 2024-01-14 20:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tournament", "0039_alter_msonlinetournamentregistration_notes"),
    ]

    operations = [
        migrations.AddField(
            model_name="msonlinetournamentregistration",
            name="is_validated",
            field=models.BooleanField(default=False),
        ),
    ]
