# -*- coding: utf-8 -*-

# Generated by Django 4.2.9 on 2024-01-30 22:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tournament", "0040_msonlinetournamentregistration_is_validated"),
    ]

    operations = [
        migrations.AlterField(
            model_name="msonlinetournamentregistration",
            name="ms_account_id",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
