# Generated by Django 4.2.9 on 2024-06-08 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tournament", "0044_alter_tournamentapplication_tournament_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="OnlineTournamentConfig",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("token", models.CharField(unique=True)),
                ("online_config", models.TextField(blank=True, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="tournament",
            name="online_config",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="tournament.onlinetournamentconfig",
            ),
        ),
    ]
