# Generated by Django 4.2.9 on 2024-06-08 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tournament", "0045_onlinetournamentconfig_tournament_online_config"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tournament",
            name="online_config",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="tournament.onlinetournamentconfig",
            ),
        ),
    ]
