# Generated by Django 4.2.13 on 2024-06-21 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tournament", "0046_alter_tournament_online_config"),
    ]

    operations = [
        migrations.AddField(
            model_name="tournament",
            name="is_command",
            field=models.BooleanField(default=False),
        ),
    ]
