# Generated by Django 4.2.14 on 2024-07-31 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tournament", "0047_tournament_is_command"),
    ]

    operations = [
        migrations.AddField(
            model_name="tournament",
            name="share_notes",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="tournamentregistration",
            name="notes",
            field=models.TextField(blank=True, default="", null=True, verbose_name="Additional info"),
        ),
    ]
