# Generated by Django 4.2.15 on 2024-08-14 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tournament", "0049_tournamentapplication_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tournamentapplication",
            old_name="user",
            new_name="tournament_admin_user",
        ),
    ]
