# Generated by Django 4.2.16 on 2024-10-27 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tournament", "0050_rename_user_tournamentapplication_tournament_admin_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tournament",
            name="is_command",
            field=models.BooleanField(default=False, verbose_name="Is team tournament"),
        ),
    ]
