# Generated by Django 5.2.7 on 2025-11-14 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tournament", "0052_alter_onlinetournamentconfig_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="tournament",
            name="is_pre_registration",
            field=models.BooleanField(default=False),
        ),
    ]
