# Generated by Django 5.2.7 on 2025-11-14 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tournament", "0053_tournament_is_pre_registration"),
    ]

    operations = [
        migrations.AddField(
            model_name="msonlinetournamentregistration",
            name="is_highlighted",
            field=models.BooleanField(default=False),
        ),
    ]
