# Generated by Django 5.1.6 on 2025-03-28 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tournament", "0054_msonlinetournamentregistration_is_highlighted"),
    ]

    operations = [
        migrations.AddField(
            model_name="msonlinetournamentregistration",
            name="confirm_code",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="onlinetournamentregistration",
            name="confirm_code",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
