# Generated by Django 5.2.7 on 2025-11-14 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tournament", "0055_msonlinetournamentregistration_confirm_code_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tournament",
            name="with_confirm_code",
            field=models.BooleanField(default=False),
        ),
    ]
