# Generated by Django 5.2.8 on 2025-12-04 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tournament", "0056_tournament_with_confirm_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="tournament",
            name="tournament_games_type",
            field=models.CharField(
                choices=[("offline", "offline"), ("online", "online")], default="offline", max_length=10
            ),
        ),
    ]
