# Generated by Django 5.2.15 on 2026-07-18 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tournament", "0057_tournament_tournament_games_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="TournamentAttribute",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100)),
                ("description", models.CharField(max_length=255)),
                ("description_en", models.CharField(max_length=255, null=True)),
                ("description_ru", models.CharField(max_length=255, null=True)),
                ("asset_path", models.CharField(max_length=255)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="tournament",
            name="attribute_is_hide",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tournament",
            name="attribute",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to="tournament.tournamentattribute"
            ),
        ),
    ]
