# Generated by Django 5.2.15 on 2026-06-28 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tournament", "0058_tournamentattribute_tournament_attribute_is_hide_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tournamentresult",
            name="player_pantheon_id",
            field=models.PositiveSmallIntegerField(blank=True, default=None, null=True),
        ),
    ]
