# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-17 06:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournamenttype',
            name='slug',
            field=models.SlugField(choices=[['rr', 'rr'], ['crr', 'crr'], ['ema', 'ema'], ['fema', 'fema'], ['other', 'other']], unique=True),
        ),
    ]
