# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-18 13:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0005_remove_tournament_tournament_type'),
        ('settings', '0002_auto_20180117_0643'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TournamentType',
        ),
    ]
