# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-29 01:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_auto_20171222_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournamenttype',
            name='slug',
            field=models.SlugField(choices=[['club', 'club'], ['ema', 'ema'], ['fema', 'fema']], unique=True),
        ),
    ]
