# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-05 03:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0003_auto_20171229_0127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournamenttype',
            name='slug',
            field=models.SlugField(choices=[['club', 'club'], ['ema', 'ema'], ['fema', 'fema'], ['other', 'other']], unique=True),
        ),
    ]
